### ISSUE TITLE
ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()

### ISSUE THREAD

**Issue by slasherx2** [kaniini/antissh#41]
ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 734, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/dist-packages/asyncirc/irc.py", line 89, in data_received
    signal("raw").send(self, text=line_received)
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/dist-packages/asyncirc/plugins/core.py", line 112, in _redispatch_raw
    signal("irc").send(message)
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/dist-packages/asyncirc/plugins/core.py", line 107, in _redispatch_irc
    signal("irc-{}".format(message.verb.lower())).send(message)
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/dist-packages/asyncirc/plugins/core.py", line 29, in _redispatch_notice
    _redispatch_message_common(message, "notice")
  File "/usr/local/lib/python3.6/dist-packages/asyncirc/plugins/core.py", line 19, in _redispatch_message_common
    signal(type).send(message, user=user, target=target, text=text)
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
TypeError: handle_connection_notice() got an unexpected keyword argument 'user'

Getting the above, any ideas please?

**Comment by nazcar4** [comment]
the same
ERROR:asyncio:Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 734, in _read_ready
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.6/site-packages/asyncirc/irc.py", line 89, in data_received
    signal("raw").send(self, text=line_received)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/asyncirc/plugins/core.py", line 112, in _redispatch_raw
    signal("irc").send(message)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/asyncirc/plugins/core.py", line 107, in _redispatch_irc
    signal("irc-{}".format(message.verb.lower())).send(message)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/asyncirc/plugins/core.py", line 29, in _redispatch_notice
    _redispatch_message_common(message, "notice")
  File "/usr/local/lib/python3.6/site-packages/asyncirc/plugins/core.py", line 19, in _redispatch_message_common
    signal(type).send(message, user=user, target=target, text=text)
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
TypeError: handle_connection_notice() got an unexpected keyword argument 'user'

**Comment by nazcar4** [comment]
solved line 322     def handle_connection_notice(_message, _user, _target, text):  change with     def handle_connection_notice(message, user, target, text):
